CREATE TABLE uploaded_image
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id   BIGINT,
    filename   VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_uploadedimage PRIMARY KEY (id)
);

ALTER TABLE uploaded_image
    ADD CONSTRAINT FK_UPLOADEDIMAGE_ON_OWNER FOREIGN KEY (owner_id) REFERENCES users (id);