-- Image upload and storage table
-- Tracks all images uploaded to MinIO buckets

CREATE TABLE uploaded_image (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id BIGINT,
    filename VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    visibility SMALLINT,
    public_url VARCHAR(255),
    public_thumbnail_url VARCHAR(255),
    publicid UUID UNIQUE,

    CONSTRAINT pk_uploadedimage PRIMARY KEY (id),
    CONSTRAINT FK_UPLOADEDIMAGE_ON_OWNER FOREIGN KEY (owner_id) REFERENCES users (id)
);

CREATE INDEX idx_uploaded_image_publicid ON uploaded_image(publicid);
