ALTER TABLE api_token ADD COLUMN type TEXT;
UPDATE api_token SET type = 'API' WHERE type IS NULL;

CREATE TABLE student_upload
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_externe BIGINT,
    team_id    BIGINT,
    url        VARCHAR(255),
    tag1       VARCHAR(255),
    tag2       VARCHAR(255),
    tag3       VARCHAR(255),
    CONSTRAINT pk_studentupload PRIMARY KEY (id)
);

ALTER TABLE student_upload
    ADD CONSTRAINT FK_STUDENTUPLOAD_ON_TEAM FOREIGN KEY (team_id) REFERENCES users (id);
